version: '3'

dotenv:
  - '.env.dev'

tasks:
  up:
    desc: 'Run docker compose and subscribe to logs'
    deps: [ down ]
    cmds:
      - docker-compose up -d
      - docker logs -f $APP

  down:
    desc: 'Stops docker compose'
    silent: true
    cmds:
      - docker-compose down --remove-orphans

  attach_hooks:
    desc: 'Attaches git hooks'
    cmds:
      - cp ./tools/prepare-commit-msg.sh ./.git/hooks/prepare-commit-msg
      - cp ./tools/pre-commit.sh ./.git/hooks/pre-commit
      - cp ./tools/pre-push.sh ./.git/hooks/pre-push
      - chmod 777 ./.git/hooks/prepare-commit-msg
      - chmod 777 ./.git/hooks/pre-commit
      - chmod 777 ./.git/hooks/pre-push

  lint:
    desc: 'Run linters'
    cmds:
      - golangci-lint run --tests=0 ./...

  test:
    desc: 'Run tests'
    cmds:
      - go test ./...

  create_migration:
    desc: "Create SQL-migration files"
    cmds:
      - migrate -database $PSQL_MIGRATE_URL -path ./migrations create -ext sql -dir ./migrations -seq -digits 6 {{.CLI_ARGS}}

  migrate:
    desc: "Shortcut for migrate tool usage"
    cmds:
      - migrate -database $PSQL_MIGRATE_URL -path ./migrations {{.CLI_ARGS}}
